function f = Hp(q_vec, p_vec, epsilon1, epsilon2, epsilon3, epsilon4, epsilon5, Hp1, Hp2, Hp3, Hp4, Hp5)
f = epsilon1*eval([Hp1,'(q_vec, p_vec)']) + epsilon2*eval([Hp2,'(q_vec, p_vec)'])...
    + epsilon3*eval([Hp3,'(q_vec, p_vec)']) + epsilon4*eval([Hp4,'(q_vec, p_vec)'])...
    + epsilon5*eval([Hp5,'(q_vec, p_vec)']);
