function f = Kp(x_vec, y_vec, lambda, epsilon1, epsilon2, epsilon3, epsilon4, epsilon5, deg1, deg2, deg3, deg4, deg5, Hp1, Hp2, Hp3, Hp4, Hp5)
% Definizione: "deg" e' il grado di omogeneita' dell'Hamiltoniana perturbatrice,
% pari al grado nelle q meno un mezzo il grado nelle p.
f = epsilon1*lambda^(2*deg1+2)*eval([Hp1,'(x_vec, y_vec)']) +...
         epsilon2*lambda^(2*deg2+2)*eval([Hp2,'(x_vec, y_vec)']) +...
         epsilon3*lambda^(2*deg3+2)*eval([Hp3,'(x_vec, y_vec)']) +...
         epsilon4*lambda^(2*deg4+2)*eval([Hp4,'(x_vec, y_vec)']) +...
         epsilon5*lambda^(2*deg5+2)*eval([Hp5,'(x_vec, y_vec)']);