% global s_o
s_o = 180/pi*2*atan(sqrt((1-Ecc_o)/(1+Ecc_o))*tan(f_o/2*pi/180));
Ecc_vers_o = [cos(pi/180*omega_o)*cos(pi/180*Omega_o)-sin(pi/180*omega_o)*sin(pi/180*Omega_o)*cos(pi/180*incl_o)...
              cos(pi/180*omega_o)*sin(pi/180*Omega_o)+sin(pi/180*omega_o)*cos(pi/180*Omega_o)*cos(pi/180*incl_o)...
              sin(pi/180*omega_o)*sin(pi/180*incl_o)];
if sm_ax_o <= 0
    warndlg('The semimajor axis must be positive')
    return
end              
G_o = sqrt(sm_ax_o*(1-Ecc_o^2));
G_vec_o = [G_o*sin(pi/180*incl_o)*sin(pi/180*Omega_o)...
          -G_o*sin(pi/180*incl_o)*cos(pi/180*Omega_o)...
           G_o*cos(pi/180*incl_o)];
q_vec_o = sm_ax_o*cos(pi/180*s_o)*Ecc_vers_o+sqrt(sm_ax_o)*sin(pi/180*s_o)*...
    vectorp(G_vec_o,Ecc_vers_o)-sm_ax_o*Ecc_o*Ecc_vers_o; 
p_vec_o = 1/(sm_ax_o*(1-Ecc_o*cos(pi/180*s_o)))*(-sqrt(sm_ax_o)*sin(pi/180*s_o)*...
    Ecc_vers_o + cos(pi/180*s_o)*vectorp(G_vec_o,Ecc_vers_o));