set(app.pushbutton_Orbits, 'Enable', 'off')
set(app.pushbutton_AA, 'Enable', 'off')
set(app.pushbutton_error, 'Enable', 'off')
set(app.pushbutton_freq, 'Enable', 'off')
set(app.pushbutton_level, 'Enable', 'off')
set(app.pushbutton_FMI, 'Enable', 'off')
